### PR TITLE
[DOC] Add tshoot section with TLS/HTTP mixed datasource

### PR DESCRIPTION
**Pull request by indigo423**
# Description

Introducing a troubleshooting section using the initial article [Using Perses with TLS and Prometheus with plain HTTP](https://github.com/perses/perses/discussions/2171).

Resolve: #2196

# Reviewer Hints

I've created a directory collecting troubleshooting articles. I have added the screenshots in the same directory. There is an "images" directory, I wasn't sure if it's a good idea to get all images in a similar spot. Just thinking out loud, do you want screenshots here? They come with a maintenance cost and they get outdated soon.

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

### CODE REVIEW

**Comment by indigo423** [comment]
@Nexucis here is a proposal for the troubleshooting section. Feel free ripping it apart :)

**Comment by Nexucis** [comment]
Yeah that's ok for me. Thank you for doing it @indigo423.

Regarding the images, I would prefer to use the github storage for that. A tips is to open an issue, then copy and past the image that will give you a link, and then use this link in the mardown file. Like that we don't store any images in git

**Comment by indigo423** [comment]
> Regarding the images, I would prefer to use the github storage for that. A tips is to open an issue, then copy and past the image that will give you a link, and then use this link in the mardown file. Like that we don't store any images in git

I've removed the images from the repository, created an issue with the screenshots for reference and used the links instead.

**Comment by Nexucis** [comment]
nice thanks @indigo423. Actually you didn't need to create an issue. Just going to the template to be able to copy and past the image to generate the link. And then you can forgot the issue once you have the links. But no worries it's just a trick.

Thank you for doing it !

**Review by Nexucis — APPROVED** [review]

**Pull request merged**
