### PR TITLE
[ENHANCEMENT] Ignore Not Found errors in percli delete command

### PR DESCRIPTION
**Pull request by kamijin-fanta**
# Description

The current `percli delete` command outputs a Not Found error when a resource is not found. This is inconvenient when using a definition file that includes multiple existing resources for deletion.

For example, the command would result in the following output.

```
$ # add new resources
$ percli apply -f sandbox.json
object "Project" "project-1" has been applied
object "Role" "defaultrole" has been applied in the project "project-1"
object "User" "user1" has been applied
object "RoleBinding" "projectrolebinding" has been applied in the project "project-1"

$ # delete resources
$ percli delete -f sandbox.json
object "Project" "project-1" has been deleted
Error: something wrong happened with the request to the API.  Message: document not found StatusCode: 404
```

In this PR, I will make changes to ignore Not found errors.

This is an implementation idea. Feedback and discussion are welcome.

# Screenshots

not ui changes

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

- [ ] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [ ] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [ ] Visual tests are stable and unlikely to be flaky.
  See [Storybook](https://github.com/perses/perses/tree/main/ui/storybook#visual-tests)
  and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues
  include:
  - Is the data inconsistent? You need to mock API requests.
  - Does the time change? You need to use consistent time values or mock time utilities.
  - Does it have loading states? You need to wait for loading to complete.

### CODE REVIEW

**Comment by Nexucis** [comment]
While I agree it can be a good idea to be more permissive in this command, the example you are showing shouldn't give you this error.

If you apply a file and then use the same file to delete the matching document, it shouldn't return an error and should work like that.
Is there a bug somewhere ? Why the command doesn't find one resource ?

**Comment by Nexucis** [comment]
regarding the way to implement it, another idea could be to collect all errors and then throw it at the end. So the command can go through all resources you wanted to delete, but at the end it gives you a full result on what happens and can fail (with error code).
What do you think ?

**Comment by kamijin-fanta** [comment]
Thank you for the review! When a project is deleted, the associated Roles and RoleBindings, etc... are also deleted. Therefore, even if you use the JSON file that was used for creation, there might be cases where deletion fails. If necessary, I can prepare the file tomorrow.

Returning an error only after all resources have been added or deleted is a good idea to enhance usability.

**Comment by Nexucis** [comment]
ah yeah you are right, I forgot that deleting the project is also deleting every resources related to the project. That makes more sense to ignore the 404 errors indeed mmm.

The issue with that is in other cases, you may want to show and return the error even if it's a 404.

**Comment by celian-garcia** [comment]
My two cent here. I agree with @kamijin-fanta that as long as it displays what it is deleting that's okay to not return error. 

Also giving a full of not existing resource file, a message "Nothing found to be deleted" could be also good instead of empty answer.

If we want to go in error, then it makes me think a bit of the #1917 issue where it seems we're going for a --force flag. That could also be another option.

**Review by Nexucis — APPROVED** [review]
alright, you convinced me :).

LGTM

**Comment by kamijin-fanta** [comment]
Thank you for the quick review and merge!

**Pull request merged**
