### PR TITLE
add documentation regarding how Perses might work on k8s

### PR DESCRIPTION
**Pull request by Nexucis**
Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

### CODE REVIEW

**Comment by Nexucis** [comment]
Hopefully I didn't miss a part on how it works, and I hope it will help you :).

**Comment by Nexucis** [comment]
yeah you are right, but I think in that case we should rely on the kubernetes permission system. So you are back in the first point where Perses is using the user token.

The second point is when you give a full access to everybody to the dashboards and this is something that cannot be done using the user token, because like explained it's unlikely a k8s SRE will give this kind of right to all users

**Review by AntoineThebaud — APPROVED** [review]

**Review by sjcobb — APPROVED** [review]
LGTM thanks for writing this up!

**Review by LukeTillman — APPROVED** [review]
Thanks for taking the time to write this up!

**Pull request merged**
