### PR TITLE
Release/v0.3

### PR DESCRIPTION
**Pull request by Nexucis**

### CODE REVIEW

**Comment by Nexucis** [comment]
It's just to have back the different changes made for this release like the `CommonJS` build.

**Comment by Nexucis** [comment]
this PR must create a merge commit and must not be squashed.

**Comment by Nexucis** [comment]
I'm wondering if we should delete the branch as well.

Do you foresee another patch for the v0.3 series @LukeTillman @sjcobb ?

**Review by LukeTillman — APPROVED** [review]
Nope, I think we're good to delete this branch. The theme changes in Steven's current PR probably warrant a `0.4` release next.

**Pull request merged**
