### PR TITLE
[ENHANCEMENT] improve search in the home page

### PR DESCRIPTION
**Pull request by Nexucis**
This PR is improving the search in the home page.

Before when you were searching for a particular dashboard, it didn't returned the dashboard that matched the search. But it returned the project with every dashboards including the one that is matching.

Result with this PR: 

image

MicrosoftTeams-image

### CODE REVIEW

**Comment by Gladorme** [comment]
Awesome 😄 LGTM

**Review by sjcobb — APPROVED** [review]
🙌

**Comment by Nexucis** [comment]
the e2e tests cannot load the `dashboardPage` in the tests `duplicatePanels.spec.ts:31:7` but it doesn't seem it's related to the changes I did.

But after running three times the tests, somehow it should be related to my changes.
Does someone have a clue of what I should do ? @sjcobb @eunicorn @juliepagano ?

**Comment by Nexucis** [comment]
and at least on this PR, the e2e tests are super slow :o

**Comment by eunicorn** [comment]
> the e2e tests cannot load the `dashboardPage` in the tests `duplicatePanels.spec.ts:31:7` but it doesn't seem it's related to the changes I did.
> 
> But after running three times the tests, somehow it should be related to my changes. Does someone have a clue of what I should do ? @sjcobb @eunicorn @juliepagano ?

It runs successfully for me when i run the tests locally 🤔

**Comment by eunicorn** [comment]
> and at least on this PR, the e2e tests are super slow :o

I see in the logs it is attempting many retries after it fails which might explains why it's slower (over 100 attempts). Maybe we should set a maximum # of retries @juliepagano

**Comment by juliepagano** [comment]
> > and at least on this PR, the e2e tests are super slow :o
> 
> I see in the logs it is attempting many retries after it fails which might explains why it's slower (over 100 attempts). Maybe we should set a maximum # of retries @juliepagano

Oh weird. I thought it was set to 3 retries. I wonder if something is messed up. Lemme take a look.

**Comment by juliepagano** [comment]
> > > and at least on this PR, the e2e tests are super slow :o
> > 
> > 
> > I see in the logs it is attempting many retries after it fails which might explains why it's slower (over 100 attempts). Maybe we should set a maximum # of retries @juliepagano
> 
> Oh weird. I thought it was set to 3 retries. I wonder if something is messed up. Lemme take a look.

It looks like it's set to 2 ([code](https://github.com/perses/perses/blob/main/ui/e2e/src/config/ci.playwright.config.ts#L29)). I only see 2 retries in the failed jobs. Does someone have a pointer to where you were seeing more than that? In the mean time...looking into why the tests are failing.

**Comment by eunicorn** [comment]
> It looks like it's set to 2 ([code](https://github.com/perses/perses/blob/main/ui/e2e/src/config/ci.playwright.config.ts#L29)). I only see 2 retries in the failed jobs. Does someone have a pointer to where you were seeing more than that? In the mean time...looking into why the tests are failing.

I downloaded the logs archive by clicking on the gear icon [here](https://github.com/perses/perses/actions/runs/4852790290/jobs/8648216466?pr=1127) 

```
2023-04-28T11:19:14.7149929Z @perses-dev/e2e:e2e:ci:     retrying click action, attempt #115
2023-04-28T11:19:14.7150174Z @perses-dev/e2e:e2e:ci:       waiting 500ms
2023-04-28T11:19:14.7150596Z @perses-dev/e2e:e2e:ci:       waiting for element to be visible, enabled and stable
2023-04-28T11:19:14.7150978Z @perses-dev/e2e:e2e:ci:       element is visible, enabled and stable
2023-04-28T11:19:14.7151286Z @perses-dev/e2e:e2e:ci:       scrolling into view if needed
2023-04-28T11:19:14.7151531Z @perses-dev/e2e:e2e:ci:       done scrolling
2023-04-28T11:19:14.7152058Z @perses-dev/e2e:e2e:ci:       <iframe src="about:blank" id="webpack-dev-server-client-…></iframe> intercepts pointer events
```

[1_end-to-end tests.txt](https://github.com/perses/perses/files/11367210/1_end-to-end.tests.txt)

**Comment by juliepagano** [comment]
> > It looks like it's set to 2 ([code](https://github.com/perses/perses/blob/main/ui/e2e/src/config/ci.playwright.config.ts#L29)). I only see 2 retries in the failed jobs. Does someone have a pointer to where you were seeing more than that? In the mean time...looking into why the tests are failing.
> 
> I downloaded the logs by clicking on the gear icon [here](https://github.com/perses/perses/actions/runs/4852790290/jobs/8648216466?pr=1127)
> 
> ```
> 2023-04-28T11:19:14.7149929Z @perses-dev/e2e:e2e:ci:     retrying click action, attempt #115
> 2023-04-28T11:19:14.7150174Z @perses-dev/e2e:e2e:ci:       waiting 500ms
> 2023-04-28T11:19:14.7150596Z @perses-dev/e2e:e2e:ci:       waiting for element to be visible, enabled and stable
> 2023-04-28T11:19:14.7150978Z @perses-dev/e2e:e2e:ci:       element is visible, enabled and stable
> 2023-04-28T11:19:14.7151286Z @perses-dev/e2e:e2e:ci:       scrolling into view if needed
> 2023-04-28T11:19:14.7151531Z @perses-dev/e2e:e2e:ci:       done scrolling
> 2023-04-28T11:19:14.7152058Z @perses-dev/e2e:e2e:ci:       <iframe src="about:blank" id="webpack-dev-server-client-…></iframe> intercepts pointer events
> ```
> 
> [1_end-to-end tests.txt](https://github.com/perses/perses/files/11367210/1_end-to-end.tests.txt)

Ah gotcha. The top-level test retries is set to 2. It looks like [actions](https://playwright.dev/docs/test-timeouts) do not have a default timeout, so unless one is specified, they'll try until they hit the test timeout, which we have set to 1 minute ([code](https://github.com/perses/perses/blob/main/ui/e2e/src/config/base.playwright.config.ts#L24)).

**Comment by juliepagano** [comment]
> > the e2e tests cannot load the `dashboardPage` in the tests `duplicatePanels.spec.ts:31:7` but it doesn't seem it's related to the changes I did.
> > But after running three times the tests, somehow it should be related to my changes. Does someone have a clue of what I should do ? @sjcobb @eunicorn @juliepagano ?
> 
> It runs successfully for me when i run the tests locally 🤔 The log complains that `<iframe src="about:blank" id="webpack-dev-server-client-…></iframe> intercepts pointer`.

I noticed there's an eslint warning, and I'm wondering if that's triggering the webpack error overlay thingy, but I can't reproduce that when running locally, so I'm not 100% sure what's going on...

> @perses-dev/app:lint: /home/runner/work/perses/perses/ui/app/src/views/home/ProjectsAndDashboards.tsx
@perses-dev/app:lint:   165:6  warning  React Hook useMemo has a missing dependency: 'data'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

**Comment by juliepagano** [comment]
I'm going to try pushing up a fix for that eslint warning to see if it magically fixes things or is a red herring.

**Comment by eunicorn** [comment]
> I'm going to try pushing up a fix for that eslint warning to see if it magically fixes things or is a red herring.

You fixed it! Amazing! I wonder what this webpack error overlay looks like. Aren't warnings usually printed in the console only?

> Ah gotcha. The top-level test retries is set to 2. It looks like [actions](https://playwright.dev/docs/test-timeouts) do not have a default timeout, so unless one is specified, they'll try until they hit the test timeout, which we have set to 1 minute ([code](https://github.com/perses/perses/blob/main/ui/e2e/src/config/base.playwright.config.ts#L24)).

I see, do you think maybe one minute is too long?

**Comment by juliepagano** [comment]
> > I'm going to try pushing up a fix for that eslint warning to see if it magically fixes things or is a red herring.
> 
> You fixed it! Amazing! I wonder what this webpack error overlay looks like. Aren't warnings usually printed in the console only?
> 
> > Ah gotcha. The top-level test retries is set to 2. It looks like [actions](https://playwright.dev/docs/test-timeouts) do not have a default timeout, so unless one is specified, they'll try until they hit the test timeout, which we have set to 1 minute ([code](https://github.com/perses/perses/blob/main/ui/e2e/src/config/base.playwright.config.ts#L24)).
> 
> I see, do you think maybe one minute is too long?

Some of the tests with a bunch of actions and clicking around take a while, but we could probably tune it down a bit. Now that I know what caused the problem, I'm going to play around with some tuning to fix it. Likely involving some combo of:
- Making eslint rules we care about errors (instead of warnings). I find warnings are easy to miss/ignore, and thus being kind of pointless.
- See if we can disable the overlay in CI (or maybe altogether? I never use it, and can't even get it to show up locally, I think I may have an env var that turns it off from other projects).
- Tweaking the timeouts a bit to reduce how long things run if something goes sideways like this.

**Comment by Nexucis** [comment]
oh cool, thank you @juliepagano for the fix.
Is it ok if we merge this PR ?

**Comment by juliepagano** [comment]
> oh cool, thank you @juliepagano for the fix. Is it ok if we merge this PR ?

I think you should be ok with the 👍  from @sjcobb and the tiny fix I added to appease the linter (it was a missing dependency in one of the react hooks). I didn't do a full code review -- let me know if you'd like me to before you merge.

**Comment by Nexucis** [comment]
it's fine, the diff is quite light and don't require a huge review :). Thanks for your help @juliepagano @sjcobb and @eunicorn !

**Pull request merged**
