### PR TITLE
Remove old datasources, shim enough to keep UI functioning

### PR DESCRIPTION
**Pull request by LukeTillman**
This just removes the old Datasources code, type definitions, etc. so that we can implement the new spec documented in #404. I left a very basic implementation in place for the legacy version just to let the UI continue functioning while we work on implementing it for real.

Signed-off-by: Luke Tillman <LukeTillman@users.noreply.github.com>

### CODE REVIEW

**Comment by Nexucis** [comment]
Nice :).
Maybe for this one, let's try to connect FE and BE directly. WDYT ?
Hopefully next week we should be able to deliver the new implem of thé datasource BE side

**Comment by LukeTillman** [comment]
> Nice :). Maybe for this one, let's try to connect FE and BE directly. WDYT ? Hopefully next week we should be able to deliver the new implem of thé datasource BE side

Yeah, definitely possible. My plan is to basically do the implementation with stubbed out API calls so we can just swap it out for a real `fetch` call to connect them.

**Comment by Nexucis** [comment]
> My plan is to basically do the implementation with stubbed out API calls so we can just swap it out for a real fetch call to connect them.

Interesting ! Do you think it would be possible to do the same for the loading of the dashboard ?

**Review by Nexucis — APPROVED** [review]

**Comment by LukeTillman** [comment]
> > My plan is to basically do the implementation with stubbed out API calls so we can just swap it out for a real fetch call to connect them.
> 
> Interesting ! Do you think it would be possible to do the same for the loading of the dashboard ?

Yeah, probably could do the same there. One thing I'd love to do when we want to make that change is to add a proper URL/route to the UI for a dashboard so we could grab the "dashboard ID" from the URL path.

**Comment by Nexucis** [comment]
> One thing I'd love to do when we want to make that change is to add a proper URL/route to the UI for a dashboard so we could grab the "dashboard ID" from the URL path.

Totally inline with that.
From my side a proposition for the URL would be `/projects/<project_name>/dashboards/<dashboard_name>`.
With `project_name` and `dashboard_name` you are able to find/get the dashboard.

**Pull request merged**
