### PR TITLE
API: add folder management

### PR DESCRIPTION
**Pull request by Nexucis**
This PR is adding a way to manage a sub-folder system in the backend. In the backend it's just a document that describes a folder tree with some references to the dashboard.

It will be used by the frontend to sort the dashboard in the different folders defined.

Note: related to the issue #183 

FYI: @LukeTillman @sjcobb 

Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
The PR generally seems fine to me, but introducing a feature as central as Folders is something that the other more active devs really need to give high-level input on as well.

One thing to be aware of: this introduces more references between things (previously we only had dashboards and datasources), so manually managing referential integrity without a relational database is already becoming one step more complex.

**Comment by Nexucis** [comment]
> The PR generally seems fine to me, but introducing a feature as central as Folders is something that the other more active devs really need to give high-level input on as well.

Of course ! I didn't try to it as a ghost haha.

> One thing to be aware of: this introduces more references between things (previously we only had dashboards and datasources), so manually managing referential integrity without a relational database is already becoming one step more complex.

Yeah this one is introducing more manual references, but I think it is still fine and it's quite easy to manage.
But that's also why it's easy to implement.  If we were using a referential databases, it's hard to manage this kind of document. I mean having a document that have a recursive definition with multiple references.

And again, we are using a K/V database (for the moment), because then moving / supporting CRD in k8s will be an easy move. Which is not when you are using a relational database.

Yes at some points we should probably support others databases :). That can make sense

**Comment by juliusv** [comment]
> But that's also why it's easy to implement. If we were using a referential databases, it's hard to manage this kind of document. I mean having a document that have a recursive definition with multiple references.

True. The current model you have here allows a dashboard to be referenced from multiple folders at the same time, kind of like a hardlink or symlink on Unix. Do you think in the end, when there's UI-based-editing features, it will also make sense to expose that kind of flexibility to the user (i.e. create a dashboard, associate it with multiple folders, almost like GMail labels)?

**Comment by Nexucis** [comment]
I think we should already prevent the possibility to link a dashboard to multiple different sub-folders. It's a sort of technical limitation because it would be hard for the UI to determinate from which folder the dashboard is coming from.

You will likely have this link `https://perses-dev/project/<your_project>/folders/<folder_name>/<dashboard_name>`. Because the number of folders you can describe in this document is not limited but the URL is limited, you won't be able to put the folder tree in the URL.

So if the dashboard is referenced in multiple sub-folder, the UI won't be able to know from which folder the dashboard is coming from. 

But if the dashboard is referenced only one time, then the UI will be able to re-build the accurate `BreadCrum` based on the URL + based on the `Folder` document.

**Comment by Nexucis** [comment]
I think I will implement something to be sure you will have only one references of a dashboard per document.

I'm wondering if we should already limit the depth you can have in term of folder hierarchy. And if yes what would be the limits ? 5, 10 ? Any opinion around this topic @juliusv @sjcobb  @LukeTillman ?

**Comment by juliusv** [comment]
For now I wouldn't worry about limiting the depth, it's something you can get back to if / when needed IMO.

**Pull request merged**
