### PR TITLE
Initial compact legend component (sumeete fork)

### PR DESCRIPTION
**Pull request by sjcobb**
Add ListLegend.tsx and ListLegendItem.tsx in @perses-dev/components package for use in TimeSeriesChart panel

Original branch here: https://github.com/sumeete/perses/tree/sumeete/listlegend
- updated with signoff, sync with upstream, removed panel changes since I'll handle those in a follow up PR

### CODE REVIEW

**Review by LukeTillman — APPROVED** [review]
👍  Interested to see this get iterated on / integrated into the chart.

**Comment by LukeTillman** [comment]
Also, thanks @sumeete !

**Comment by Nexucis** [comment]
does it change the datamodel of the TimeSeriesChart ?

**Comment by sjcobb** [comment]
> does it change the datamodel of the TimeSeriesChart ?

Not yet! This is just the component without any changes to the panel, I'll be making changes to the panel in separate PR soon

**Pull request merged**
