### PR TITLE
[DOC] Fix broken link to the contributing guide in the introduction page

### PR DESCRIPTION
**Pull request by Romain-Geissler-1A**
# Description

Fix broken link to the contributing guide in the introduction page.

[joke] Given that I contribute a very critical change in Perses, I guess I deserve my name in the MAINTAINERS file no ? :p [/joke]

# Checklist

- [X] Pull request has a descriptive title and context useful to a reviewer.
- [X] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [X] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

### CODE REVIEW

**Review by celian-garcia — APPROVED** [review]

**Comment by celian-garcia** [comment]
Haha thank you Romain! 😋
The maintainers file is not maintained. I'm wondering if we should maintain it... 

You for whom the opensources projects have no secret, this is useless no?

**Review by AntoineThebaud — APPROVED** [review]
LGTM, still I wonder if we could later make a relative link work here. It's quite convenient in the IDE when such link opens the local file instead of the origin's one, but I don't think we want to host CONTRIBUTING.md on the static website..

**Comment by Romain-Geissler-1A** [comment]
> Haha thank you Romain! 😋 The maintainers file is not maintained. I'm wondering if we should maintain it...
> 
> You for whom the opensources projects have no secret, this is useless no?

(answering seriously for once ;) )

I have contributed (usually small useless trivial patches like this one) to about a hundred different repositories in diverse technologies, and the only thing I conclude is that there are as many open source policies as there are repositories. Everyone works differently and there is no "good" way which seems to be used by a majority. What we often see (including in our own proprietary software inside Amadeus) is that doc is often outdated the next day it was committed, so I personally trust only the source code. For the maintainers file, it shouldn't be hard to keep it up to date, I doubt it changes often anyway. Normally the time it was updated is when I passed by your office and laughed at @Gladorme because he we still not officially appointed maintainer :D So keep this file updated, it's not hard.

Finally: honestly people care much more about having the code maintained, and their issues fixed/investigated/replied to, and that you don't have a crazy huge contribution process, than looking at who maintains what ;) Just be friendly and care for your users, this is the most important thing, which I can tell you is lacking in many open source projects !

**Comment by celian-garcia** [comment]
> Normally the last time it was updated is when I passed by your office and laughed at @Gladorme because he we still not officially appointed maintainer :D So keep this file updated, it's not hard.

That must be that yeah haha. Thanks for these wised words. We're making our best to make our new contributors feel good and eager to come back.

> LGTM, still I wonder if we could later make a relative link work here. It's quite convenient in the IDE when such link opens the local file instead of the origin's one, but I don't think we want to host CONTRIBUTING.md on the static website..

Sure! and you know I like this tool checking if the URL are still valid. Maybe there is an option to verify the relative links?

**Pull request merged**
