### PR TITLE
[IGNORE] build main app using rs-pack

### PR DESCRIPTION
**Pull request by jgbernalp**
# Description

Use rsPack for the main app in preparation for dynamic plugins at runtime

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

### CODE REVIEW

**Comment by AntoineThebaud** [comment]
@jgbernalp I see that the content from this PR is logically also present in https://github.com/perses/perses/pull/2091, WDYT about creating a feature branch for the new plugin runtime, so that we merge this PR there and rebase your new one on it?

**Comment by jgbernalp** [comment]
@AntoineThebaud, that's a great suggestion. I targeted this PR to the new `feature/plugin-runtime` branch

**Comment by AntoineThebaud** [comment]
'going to fix the broken link issue in doc in another PR

**Review by AntoineThebaud — APPROVED** [review]

**Comment by AntoineThebaud** [comment]
@jgbernalp let's merge this one shall we?

**Pull request merged**
