### PR TITLE
[ENHANCEMENT] Add decimal migrations; Add barchart migration

### PR DESCRIPTION
**Pull request by 7840vz**
# Description

This adds bargauge->barchart migration and decimal places migration.

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

### CODE REVIEW

**Comment by Nexucis** [comment]
Thank you for the enhancement! Do you mind to target the branch release/v0.49 @7840vz ? Like that we can include it in the next rc for the v0.49.0 :)

**Comment by 7840vz** [comment]
done

**Comment by Nexucis** [comment]
would you mind to rebase your PR base on the new branch ? There are some commit that are not related to your PR here

**Comment by 7840vz** [comment]
rebased.

**Comment by Nexucis** [comment]
awesome thank you @7840vz !
It looks ok for me, but I would prefer @AntoineThebaud to confirm it :)

**Review by AntoineThebaud — COMMENTED** [review]
Thanks for doing that! Could you just please add a unit test covering the barchart panel migration? Here 'would be better to add a new test with a new grafana json containing a single barchart panel only, rather than appending stuff to the simple_grafana_dashboard which is quite big already

**Comment by 7840vz** [comment]
Added test

**Review by AntoineThebaud — APPROVED** [review]
🙏

**Pull request merged**
