### PR TITLE
[ENHANCEMENT] Autocomplete & filtering for ListVariable

### PR DESCRIPTION
**Pull request by AntoineThebaud**
# Description

This PR changes ListVariable to rely on MUI's Autocomplete, in order to provide autocomplete & filtering.

https://github.com/perses/perses/assets/7058693/c3a3b4df-40ab-4ec0-b22b-2e83844c6b07

Making the display fit well & adapt to the content as much as possible was not easy.. a remaining pain point is that the input grows vertically with the content (especially annoying in case of long variable values for which `limitTags={3}` is not enough, eg:
2023-11-08_18h29_13

Besides there's an annoying bug with the Autocomplete, the scroll goes to the top each time you click a value. This should be solved by upgrading the MUI dependency (see https://github.com/mui/material-ui/issues/29508). I'm planning to tackle this in a next PR.

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

- [x] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [x] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [x] Visual tests are stable and unlikely to be flaky. See [Storybook](https://github.com/perses/perses/tree/main/ui/storybook#visual-tests) and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues include:
  - Is the data inconsistent? You need to mock API requests.
  - Does the time change? You need to use consistent time values or mock time utilities.
  - Does it have loading states? You need to wait for loading to complete.

### CODE REVIEW

**Review by sjcobb — APPROVED** [review]
Nice! Someday it could be cool to potentially virtualize it using react-virtuoso for best performance

**Comment by Nexucis** [comment]
Did you succeed to keep the `LinearProgress` working ? (it is shown when the variable is loading) That was the thing I wasn't able to do so and blocked me :(

**Comment by AntoineThebaud** [comment]
> Did you succeed to keep the `LinearProgress` working ? (it is shown when the variable is loading) That was the thing I wasn't able to do so and blocked me :(

Well I don't remember changing this part but anyway it seems to be working fine.

https://github.com/perses/perses/assets/7058693/d4166c15-04de-456d-aa29-21b2ffb04929

**Review by Nexucis — APPROVED** [review]
:rabbit:

**Pull request merged**
